### ISSUE TITLE
Panic on Linux: uniform buffer binding range exceeds `max_uniform_buffer_binding_size` limit'

### ISSUE THREAD

**Issue by barafael** [Yatekii/sailor#5]
Panic happens on debug and release:

thread 'main' panicked at 'uniform buffer binding range exceeds `max_uniform_buffer_binding_size` limit', /home/ra/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:1323:35
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a2f8f6281817d430e20726128b739d3c6708561c/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/a2f8f6281817d430e20726128b739d3c6708561c/library/std/src/panicking.rs:435:5
   2: <core::result::Result<T,E> as wgpu::backend::direct::PrettyResult<T>>::unwrap_pretty::{{closure}}
             at /home/ra/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:1323:35
   3: core::result::Result<T,E>::unwrap_or_else
             at /home/ra/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:821:23
   4: <core::result::Result<T,E> as wgpu::backend::direct::PrettyResult<T>>::unwrap_pretty
             at /home/ra/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:1323:9
   5: <wgpu::backend::direct::Context as wgpu::Context>::device_create_bind_group
             at /home/ra/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:660:9
   6: wgpu::Device::create_bind_group
             at /home/ra/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/lib.rs:1443:17
   7: sailor::drawing::painter::Painter::create_blend_bind_group
             at ./src/bin/drawing/painter.rs:430:9
   8: sailor::drawing::painter::Painter::init
             at ./src/bin/drawing/painter.rs:189:26
   9: sailor::main
             at ./src/bin/main.rs:39:23
  10: core::ops::function::FnOnce::call_once
             at /home/ra/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
 ERROR gfx_memory::heaps > Heaps not completely freed before drop. Utilization: MemoryHeapUtilization { utilization: MemoryUtilization { used: 41793024, effective: 20703744 }, size: 8321499136 }
 ERROR gfx_memory::heaps > Heaps not completely freed before drop. Utilization: MemoryHeapUtilization { utilization: MemoryUtilization { used: 16777216, effective: 256096 }, size: 8573157376 }
 ERROR gfx_memory::allocator::general > Memory leak: SizeEntry(9371648) is still used
 ERROR gfx_memory::allocator::general > Memory leak: SizeEntry(2359296) is still used
 ERROR gfx_memory::allocator::general > Memory leak: SizeEntry(10944512) is still used
 ERROR gfx_memory::allocator::general > Memory leak: SizeEntry(2752512) is still used
 ERROR gfx_memory::allocator::general > Memory leak: SizeEntry(192256) is still used
 ERROR gfx_memory::allocator::general > Memory leak: SizeEntry(48064) is still used
 ERROR gfx_memory::allocator::general > Memory leak: SizeEntry(64256) is still used
 ERROR gfx_memory::allocator::linear  > Not all allocations from LinearAllocator were freed
 ERROR gfx_descriptor::allocator      > DescriptorAllocator is dropped

rustc --version:
rustc 1.51.0-nightly (a2f8f6281 2021-01-27)
rustc 1.49.0 (e1884a8e3 2020-12-29)

**Comment by Yatekii** [comment]
Fixed =)
